export const RequisitosPorUF: Record<string, string[]> = {
  DF: ['renavam'],
  MG: ['renavam'],
  GO: ['renavam'],
  AC: ['renavam', 'cpfCnpj'],
  AL: ['renavam'],
  AM: ['renavam'],
  AP: ['renavam'],
  BA: ['renavam'],
  ES: ['renavam'],
  MS: ['renavam'],
  MA: ['renavam', 'cpfCnpj'],
  MT: ['renavam', 'chassi'],
  PB: ['renavam'],
  PE: ['renavam', 'cpfCnpj'],
  PI: ['renavam', 'cpfCnpj'],
  RN: ['renavam'],
  RR: ['renavam'],
  TO: ['renavam', 'cpfCnpj'],
  RO: ['renavam'],
  RS: ['renavam', 'cpfCnpj'],
  SC: ['renavam', 'cpfCnpj'],
  CE: ['renavam', 'cpfCnpj'],
  SP: ['renavam'],
  RJ: ['renavam', 'cpfCnpj'],
  PR: ['renavam', 'cpfCnpj'],
  PA: ['renavam', 'cpfCnpj'],
};
